#spring  setup and common configuration
spring:
  profiles:
    active: local

server:
  port: 8099

---
#spring profiles : LOCAL
#spring and hikari setup
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/basquiat

#logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
